CREATE TABLE "project_documents" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "projectId" integer NOT NULL,
  "ownerUserId" integer,
  "fileName" varchar(255) NOT NULL,
  "mimeType" varchar(120) NOT NULL,
  "sizeBytes" integer NOT NULL,
  "content" bytea NOT NULL,
  "extractedText" text,
  "analysisStatus" varchar(32) DEFAULT 'pending' NOT NULL,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "project_documents" ADD CONSTRAINT "project_documents_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "project_documents" ADD CONSTRAINT "project_documents_ownerUserId_users_id_fk" FOREIGN KEY ("ownerUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "project_documents_project_idx" ON "project_documents" USING btree ("projectId");
--> statement-breakpoint
CREATE INDEX "project_documents_project_status_idx" ON "project_documents" USING btree ("projectId","analysisStatus");
