CREATE TABLE "arquimedes_capabilities" (
  "id" varchar(120) PRIMARY KEY,
  "kind" varchar(32) NOT NULL,
  "name" varchar(180) NOT NULL,
  "version" varchar(40) NOT NULL,
  "domain" varchar(120) NOT NULL,
  "description" text NOT NULL,
  "status" varchar(24) DEFAULT 'available' NOT NULL,
  "enabled" boolean DEFAULT false NOT NULL,
  "removable" boolean DEFAULT true NOT NULL,
  "dependenciesJson" text DEFAULT '[]' NOT NULL,
  "installedBy" integer,
  "installedAt" timestamp with time zone,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX "arquimedes_capabilities_status_idx" ON "arquimedes_capabilities" ("status");
CREATE INDEX "arquimedes_capabilities_kind_idx" ON "arquimedes_capabilities" ("kind");

ALTER TABLE "arquimedes_capabilities"
  ADD CONSTRAINT "arquimedes_capabilities_installedBy_users_id_fk"
  FOREIGN KEY ("installedBy") REFERENCES "users"("id");

CREATE TABLE "arquimedes_capability_events" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "capabilityId" varchar(120) NOT NULL,
  "userId" integer,
  "action" varchar(40) NOT NULL,
  "fromStatus" varchar(40),
  "toStatus" varchar(40),
  "detail" text,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX "arquimedes_capability_events_capability_idx"
  ON "arquimedes_capability_events" ("capabilityId", "createdAt");
CREATE INDEX "arquimedes_capability_events_user_idx"
  ON "arquimedes_capability_events" ("userId", "createdAt");

ALTER TABLE "arquimedes_capability_events"
  ADD CONSTRAINT "arquimedes_capability_events_capabilityId_fk"
  FOREIGN KEY ("capabilityId") REFERENCES "arquimedes_capabilities"("id") ON DELETE CASCADE;

ALTER TABLE "arquimedes_capability_events"
  ADD CONSTRAINT "arquimedes_capability_events_userId_users_id_fk"
  FOREIGN KEY ("userId") REFERENCES "users"("id");
