import { trpc } from "@/lib/trpc";
import { CalendarRange, GitBranch, Gauge, Plus, Users } from "lucide-react";
import { useState } from "react";

const resourceLabels = { mao_de_obra: "Mão de obra", equipamento: "Equipamento", material: "Material" };

export function PlanningView({ projectId, projectName }: { projectId: number; projectName: string }) {
  const utils = trpc.useUtils();
  const query = trpc.planning.list.useQuery({ projectId });
  const [resourceName, setResourceName] = useState("");
  const [resourceType, setResourceType] = useState<"mao_de_obra" | "equipamento" | "material">("mao_de_obra");
  const [resourceUnit, setResourceUnit] = useState("equipe");
  const [capacity, setCapacity] = useState("");
  const [activityName, setActivityName] = useState("");
  const [activityCode, setActivityCode] = useState("");
  const [activityPhase, setActivityPhase] = useState("Execução");
  const [activityQuantity, setActivityQuantity] = useState("");
  const [activityProductivity, setActivityProductivity] = useState("");
  const [activityDuration, setActivityDuration] = useState("");
  const [predecessorId, setPredecessorId] = useState("");
  const [successorId, setSuccessorId] = useState("");
  const refresh = () => utils.planning.list.invalidate({ projectId });
  const createResource = trpc.planning.createResource.useMutation({ onSuccess: async () => { setResourceName(""); setCapacity(""); await refresh(); } });
  const createActivity = trpc.planning.createActivity.useMutation({ onSuccess: async () => { setActivityName(""); setActivityCode(""); setActivityQuantity(""); setActivityProductivity(""); setActivityDuration(""); await refresh(); } });
  const createDependency = trpc.planning.createDependency.useMutation({ onSuccess: async () => { setPredecessorId(""); setSuccessorId(""); await refresh(); } });
  const calculateCpm = trpc.planning.calculateCpm.useMutation({ onSuccess: async () => { await refresh(); } });
  const resources = query.data?.resources ?? [];
  const activities = query.data?.activities ?? [];
  const dependencies = query.data?.dependencies ?? [];

  return <div className="module-page planning-page">
    <div className="module-hero"><div className="module-icon"><CalendarRange size={22} /></div><div><p className="eyebrow accent">PLANEJAMENTO FÍSICO</p><h2>Planejamento e rede</h2><p>{projectName} · atividades, recursos, produtividade e precedências.</p></div><span className="module-hero-status"><span /> Etapa 6 · CPM calculável</span></div>
    <div className="catalog-summary-grid"><div className="module-card budget-summary-card"><span className="eyebrow">ATIVIDADES</span><strong>{activities.length}</strong><p>Serviços planejados na obra.</p></div><div className="module-card budget-summary-card"><span className="eyebrow">RECURSOS</span><strong>{resources.length}</strong><p>Equipes, equipamentos e materiais.</p></div><div className="module-card budget-summary-card budget-total-card"><span className="eyebrow">CRÍTICAS</span><strong>{activities.filter(item => item.critical === 1).length}</strong><p>Atividades no caminho crítico persistido.</p></div></div>
    <section className="module-card cpm-panel"><div className="panel-heading"><div><h3>Cronograma calculado</h3><p>O CPM usa as durações e precedências cadastradas para calcular datas relativas e folgas.</p></div><Gauge size={18} className="sparkle" /></div><div className="cpm-actions"><button className="primary-button" disabled={calculateCpm.isPending || activities.length === 0} onClick={() => calculateCpm.mutate({ projectId })}><Gauge size={14} /> {calculateCpm.isPending ? "Calculando..." : "Calcular CPM"}</button><span>{activities.some(item => item.cpmCalculatedAt) ? `Último cálculo: ${new Date(activities.find(item => item.cpmCalculatedAt)?.cpmCalculatedAt ?? "").toLocaleString("pt-BR")}` : "Ainda não calculado"}</span></div>{calculateCpm.data && !calculateCpm.data.valid && <p className="form-error">Não foi possível calcular: {calculateCpm.data.issues.map(issue => issue.message).join("; ")}</p>}{calculateCpm.data?.valid && <div className="cpm-result"><div><span className="eyebrow">DURAÇÃO DO PROJETO</span><strong>{calculateCpm.data.projectDuration} dias</strong></div><div><span className="eyebrow">CAMINHO CRÍTICO</span><strong>{calculateCpm.data.criticalPath.length} atividades</strong></div><div className="cpm-path"><span className="eyebrow">SEQUÊNCIA</span><p>{calculateCpm.data.criticalPath.join(" → ") || "Nenhuma atividade crítica"}</p></div></div>}</section>
    <div className="planning-grid">
      <section className="module-card"><div className="panel-heading"><div><h3>Novo recurso</h3><p>Cadastre a capacidade diária para calcular prazos realistas.</p></div><Users size={18} className="sparkle" /></div><form className="planning-form-grid" onSubmit={event => { event.preventDefault(); if (resourceName && resourceUnit) createResource.mutate({ projectId, name: resourceName, resourceType, unit: resourceUnit, capacityPerDay: capacity ? Number(capacity) : undefined }); }}><label>Nome<input value={resourceName} onChange={event => setResourceName(event.target.value)} placeholder="Equipe de alvenaria" required /></label><label>Tipo<select value={resourceType} onChange={event => setResourceType(event.target.value as typeof resourceType)}>{Object.entries(resourceLabels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label>Unidade<input value={resourceUnit} onChange={event => setResourceUnit(event.target.value)} placeholder="equipe" required /></label><label>Capacidade/dia<input type="number" min="0.001" step="0.001" value={capacity} onChange={event => setCapacity(event.target.value)} placeholder="12,000" /></label><button className="primary-button" disabled={createResource.isPending}><Plus size={14} /> Cadastrar recurso</button></form><div className="planning-list">{resources.map(resource => <div className="planning-row" key={resource.id}><div><strong>{resource.name}</strong><span>{resourceLabels[resource.resourceType]} · {resource.unit}</span></div><b>{resource.capacityPerDay ? `${resource.capacityPerDay}/dia` : "capacidade pendente"}</b></div>)}{!resources.length && <div className="module-empty">Nenhum recurso cadastrado.</div>}</div></section>
      <section className="module-card"><div className="panel-heading"><div><h3>Nova atividade</h3><p>Quantidade e produtividade derivam a duração quando informadas.</p></div><CalendarRange size={18} className="sparkle" /></div><form className="planning-form-grid" onSubmit={event => { event.preventDefault(); if (activityName && activityCode && activityPhase) createActivity.mutate({ projectId, wbsCode: activityCode, name: activityName, phase: activityPhase, startOffset: 0, plannedQuantity: activityQuantity ? Number(activityQuantity) : undefined, productivity: activityProductivity ? Number(activityProductivity) : undefined, durationDays: activityDuration ? Number(activityDuration) : undefined }); }}><label>Código EAP<input value={activityCode} onChange={event => setActivityCode(event.target.value)} placeholder="1.2.3" required /></label><label className="planning-field-wide">Atividade<input value={activityName} onChange={event => setActivityName(event.target.value)} placeholder="Executar alvenaria" required /></label><label>Fase<input value={activityPhase} onChange={event => setActivityPhase(event.target.value)} placeholder="Execução" required /></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={activityQuantity} onChange={event => setActivityQuantity(event.target.value)} placeholder="120,000" /></label><label>Produtividade<input type="number" min="0.001" step="0.001" value={activityProductivity} onChange={event => setActivityProductivity(event.target.value)} placeholder="12,000/dia" /></label><label>Duração<input type="number" min="1" step="1" value={activityDuration} onChange={event => setActivityDuration(event.target.value)} placeholder="Calculada" /></label><button className="primary-button" disabled={createActivity.isPending}><Plus size={14} /> Criar atividade</button></form><div className="planning-list">{activities.map(activity => <div className="planning-row" key={activity.id}><div><strong>{activity.wbsCode} · {activity.name}</strong><span>{activity.phase} · {activity.plannedQuantity ? `${activity.plannedQuantity} planejados` : "quantidade pendente"}{activity.earlyStart !== null && activity.earlyStart !== undefined ? ` · início ${activity.earlyStart} · folga ${activity.totalFloat ?? 0}d` : ""}</span></div><b className={activity.critical === 1 ? "critical-mark" : ""}>{activity.critical === 1 ? "CRÍTICA · " : ""}{activity.durationDays} dias</b></div>)}{!activities.length && <div className="module-empty">Nenhuma atividade cadastrada.</div>}</div></section>
    </div>
    <section className="module-card"><div className="panel-heading"><div><h3>Rede de precedências</h3><p>A primeira relação estruturada da rede do cronograma. O padrão inicial é término-início.</p></div><GitBranch size={18} className="sparkle" /></div><form className="dependency-form" onSubmit={event => { event.preventDefault(); if (predecessorId && successorId) createDependency.mutate({ projectId, predecessorId: Number(predecessorId), successorId: Number(successorId), type: "FS", lag: 0 }); }}><select value={predecessorId} onChange={event => setPredecessorId(event.target.value)}><option value="">Predecessora</option>{activities.map(activity => <option key={activity.id} value={activity.id}>{activity.wbsCode} · {activity.name}</option>)}</select><span>→</span><select value={successorId} onChange={event => setSuccessorId(event.target.value)}><option value="">Sucessora</option>{activities.map(activity => <option key={activity.id} value={activity.id}>{activity.wbsCode} · {activity.name}</option>)}</select><button className="outline-button" disabled={!predecessorId || !successorId || createDependency.isPending}><Plus size={13} /> Adicionar FS</button></form><div className="planning-list">{dependencies.map(dependency => <div className="planning-row" key={dependency.id}><div><strong>{activities.find(item => item.id === dependency.predecessorId)?.name ?? `Atividade ${dependency.predecessorId}`} → {activities.find(item => item.id === dependency.successorId)?.name ?? `Atividade ${dependency.successorId}`}</strong><span>Tipo {dependency.type} · defasagem {dependency.lag} dias</span></div><b>Rede</b></div>)}{!dependencies.length && <div className="module-empty">Nenhuma precedência cadastrada.</div>}</div></section>
  </div>;
}
